name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Setiap tengah malam (UTC)
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: xr-wahyuu
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
